### ISSUE TITLE
Parameters used to create Gabor kernels

### ISSUE THREAD

**Issue by noname202** [akisatok/pySaliencyMap#5]
Hi,
I recently used code from a repository which is based on pySaliencyMap. When working with the code I wondered where the values used for the Gabor kernels come from (respectively which parameters were used to create them). When comparing results to other implementations of Itti-Koch saliency maps I also noticed that the orientation feature maps created differ from those created by other implementations.  Applying the kernels seems to have more of a "sharpening" effect. Therefore, I'd really appreciate it if you could clearify how these kernels were created.

**Comment by akisatok** [comment]
@noname202  My implementation is based on the original implementation http://ilab.usc.edu/toolkit/, and the variance parameters of the Gabor kernel are adjusted so that sm.SMGetSalientRegion produces reasonably good results.

**Comment by noname202** [comment]
@noname202 Hey akisatok,
thanks for clarifying and apologies for not responding. I must have somehow missed your response.
